// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGNzg9cb4o7Q0XIxllTBJPTKeh4dMv9OQ',
    appId: '1:37037021755:web:fdf844b34659577b129a1e',
    messagingSenderId: '37037021755',
    projectId: 'chatly-25058',
    authDomain: 'chatly-25058.firebaseapp.com',
    storageBucket: 'chatly-25058.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUcIjlGlTY-TQnakP_t-fvfJP38ivRLlw',
    appId: '1:37037021755:android:0ea1562f98a6e577129a1e',
    messagingSenderId: '37037021755',
    projectId: 'chatly-25058',
    storageBucket: 'chatly-25058.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6mG1eqdLV12zPbWN7e-3kqdaWQq_5eic',
    appId: '1:37037021755:ios:84b59839e74b572b129a1e',
    messagingSenderId: '37037021755',
    projectId: 'chatly-25058',
    storageBucket: 'chatly-25058.appspot.com',
    iosBundleId: 'com.example.chatly',
  );
}
